version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: psychologia-backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=${DATABASE_CLIENT:-sqlite}
      - DATABASE_FILENAME=${DATABASE_FILENAME:-.tmp/data.db}
    volumes:
      - ./backend/.tmp:/app/.tmp
      - ./backend/public/uploads:/app/public/uploads
    ports:
      - "127.0.0.1:13389:1337"
    networks:
      - psychologia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        PUBLIC_STRAPI_URL: http://cms.psychologiamarketingu.edu.pl
        STRAPI_URL: http://backend:1337
    container_name: psychologia-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_STRAPI_URL=http://cms.psychologiamarketingu.edu.pl
      - STRAPI_URL=http://backend:1337
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - HOST=0.0.0.0
    volumes:
      - ./frontend-dist:/app/dist
    depends_on:
      - backend
    # We use a custom entrypoint to ensure runtime sync
    command: [ "sh", "./entrypoint.sh" ]
    networks:
      - psychologia-network

networks:
  psychologia-network:
    driver: bridge
